;config file for yusen.exe 
VID=0x054C 
PID=0x0E63	;set Model: Essence4=0x0D8C / set Model: PHIL=0x0DDF / set Model: HCTW2=0x0E63
WAIT_TIME=10	;wait time (msec) per packet data transmitting during update 
TIMEOUT=5000	;timeout (msec) if no response
HASH_ONOFF=1	;set hash checking, 1 for hash checking
MODEL=3		;set Model: Essence4=1 / set Model: PHIL=2 / set Model: HCTW2=3
TIMEOUT_HELO2=1000	;timeout (msec) if no response for "helo2" command
RETRY_NUM_HELO2=0	;number of retry if no response for "helo2" command